import React, { useState, useMemo } from "react";
import { generate2DLatticeGrid, gramSchmidt2D } from "../../lib/pqcMath";
import { Grid, Eye, Sliders, Shield, Zap, Sparkles, HelpCircle } from "lucide-react";

export const LatticeVisualizer: React.FC = () => {
  // Basis vectors b1 and b2
  const [b1, setB1] = useState<[number, number]>([35, 10]);
  const [b2, setB2] = useState<[number, number]>([12, 40]);
  const [showGoodVsBad, setShowGoodVsBad] = useState<boolean>(false);
  const [targetPoint, setTargetPoint] = useState<{ x: number; y: number } | null>({ x: 75, y: 65 });
  const [showGramSchmidt, setShowGramSchmidt] = useState<boolean>(false);

  // Preset basis configurations
  const setPresetBasis = (type: "orthogonal" | "skewed" | "kyber-toy") => {
    if (type === "orthogonal") {
      setB1([45, 0]);
      setB2([0, 45]);
    } else if (type === "skewed") {
      setB1([60, 20]);
      setB2([75, 25]); // Almost parallel bad basis
    } else {
      setB1([35, 12]);
      setB2([15, 38]);
    }
  };

  const latticePoints = useMemo(() => {
    return generate2DLatticeGrid(b1, b2, 5);
  }, [b1, b2]);

  const gs = useMemo(() => {
    return gramSchmidt2D(b1, b2);
  }, [b1, b2]);

  // Find closest point to target
  const closestPoint = useMemo(() => {
    if (!targetPoint) return null;
    let minD = Infinity;
    let best = null;
    for (const p of latticePoints) {
      const d = Math.hypot(p.x - targetPoint.x, p.y - targetPoint.y);
      if (d < minD) {
        minD = d;
        best = p;
      }
    }
    return best;
  }, [targetPoint, latticePoints]);

  return (
    <div className="space-y-6">
      {/* Header Info */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-5 shadow-xl">
        <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-slate-800">
          <div>
            <div className="flex items-center space-x-2">
              <span className="px-2.5 py-0.5 rounded-full bg-cyan-950 text-cyan-400 border border-cyan-800 text-xs font-mono font-semibold">
                Geometric Cryptanalysis
              </span>
              <h3 className="text-lg font-bold text-slate-100">
                Interactive Lattice & Shortest Vector Problem (SVP)
              </h3>
            </div>
            <p className="text-xs text-slate-400 mt-1">
              Lattices are discrete periodic vector spaces generated by integer linear combinations of basis vectors. Lattice problems resist Shor's quantum algorithm because they lack hidden subgroup periodicity.
            </p>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={() => setPresetBasis("orthogonal")}
              className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium border border-slate-700"
            >
              Orthogonal Basis
            </button>
            <button
              onClick={() => setPresetBasis("kyber-toy")}
              className="px-3 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-medium shadow-md shadow-cyan-600/20"
            >
              Standard Basis
            </button>
            <button
              onClick={() => setPresetBasis("skewed")}
              className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium border border-slate-700"
            >
              Bad Skewed Basis
            </button>
          </div>
        </div>

        {/* Basis Vector Controls */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4 text-xs">
          <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
            <div className="flex justify-between items-center text-slate-300 font-semibold">
              <span className="text-emerald-400">Basis Vector b₁ = [{b1[0]}, {b1[1]}]</span>
              <span className="font-mono text-slate-500">||b₁|| = {Math.hypot(b1[0], b1[1]).toFixed(1)}</span>
            </div>
            <div className="flex items-center space-x-3">
              <span className="text-slate-400 w-6">X:</span>
              <input
                type="range"
                min="10"
                max="80"
                value={b1[0]}
                onChange={(e) => setB1([Number(e.target.value), b1[1]])}
                className="flex-1 accent-emerald-500"
              />
              <span className="text-slate-400 w-6">Y:</span>
              <input
                type="range"
                min="-40"
                max="60"
                value={b1[1]}
                onChange={(e) => setB1([b1[0], Number(e.target.value)])}
                className="flex-1 accent-emerald-500"
              />
            </div>
          </div>

          <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
            <div className="flex justify-between items-center text-slate-300 font-semibold">
              <span className="text-cyan-400">Basis Vector b₂ = [{b2[0]}, {b2[1]}]</span>
              <span className="font-mono text-slate-500">||b₂|| = {Math.hypot(b2[0], b2[1]).toFixed(1)}</span>
            </div>
            <div className="flex items-center space-x-3">
              <span className="text-slate-400 w-6">X:</span>
              <input
                type="range"
                min="-40"
                max="60"
                value={b2[0]}
                onChange={(e) => setB2([Number(e.target.value), b2[1]])}
                className="flex-1 accent-cyan-500"
              />
              <span className="text-slate-400 w-6">Y:</span>
              <input
                type="range"
                min="10"
                max="80"
                value={b2[1]}
                onChange={(e) => setB2([b2[0], Number(e.target.value)])}
                className="flex-1 accent-cyan-500"
              />
            </div>
          </div>
        </div>
      </div>

      {/* SVG Lattice Canvas */}
      <div className="relative w-full h-[460px] rounded-2xl bg-slate-950 border border-slate-800 overflow-hidden shadow-2xl flex flex-col justify-between">
        {/* Floating Toggles */}
        <div className="absolute top-3 left-3 z-10 flex space-x-2">
          <button
            onClick={() => setShowGramSchmidt(!showGramSchmidt)}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${
              showGramSchmidt
                ? "bg-purple-500/20 text-purple-300 border-purple-500/40"
                : "bg-slate-900/90 text-slate-400 border-slate-800 hover:text-slate-200"
            }`}
          >
            Gram-Schmidt (b*₁, b*₂)
          </button>
        </div>

        <svg
          viewBox="-300 -200 600 400"
          className="w-full h-full cursor-crosshair select-none"
          onClick={(e) => {
            const rect = e.currentTarget.getBoundingClientRect();
            const svgX = ((e.clientX - rect.left) / rect.width) * 600 - 300;
            const svgY = ((e.clientY - rect.top) / rect.height) * 400 - 200;
            setTargetPoint({ x: Math.round(svgX), y: Math.round(svgY) });
          }}
        >
          {/* Axis lines */}
          <line x1="-300" y1="0" x2="300" y2="0" stroke="rgba(148, 163, 184, 0.15)" strokeWidth="1" />
          <line x1="0" y1="-200" x2="0" y2="200" stroke="rgba(148, 163, 184, 0.15)" strokeWidth="1" />

          {/* Fundamental Parallelepiped */}
          <polygon
            points={`0,0 ${b1[0]},${b1[1]} ${b1[0] + b2[0]},${b1[1] + b2[1]} ${b2[0]},${b2[1]}`}
            fill="rgba(6, 182, 212, 0.08)"
            stroke="rgba(6, 182, 212, 0.3)"
            strokeWidth="1.5"
            strokeDasharray="4 2"
          />

          {/* Lattice Points */}
          {latticePoints.map((p, i) => (
            <g key={i}>
              <circle
                cx={p.x}
                cy={p.y}
                r={p.isShortest ? 5 : 3}
                fill={p.isShortest ? "#10b981" : "#475569"}
                className="transition-all"
              />
              {p.isShortest && (
                <circle
                  cx={p.x}
                  cy={p.y}
                  r="9"
                  fill="none"
                  stroke="#10b981"
                  strokeWidth="1"
                  strokeDasharray="2 2"
                />
              )}
            </g>
          ))}

          {/* Basis Vector 1 Arrow */}
          <line
            x1="0"
            y1="0"
            x2={b1[0]}
            y2={b1[1]}
            stroke="#10b981"
            strokeWidth="2.5"
            markerEnd="url(#arrow-green)"
          />

          {/* Basis Vector 2 Arrow */}
          <line
            x1="0"
            y1="0"
            x2={b2[0]}
            y2={b2[1]}
            stroke="#06b6d4"
            strokeWidth="2.5"
            markerEnd="url(#arrow-cyan)"
          />

          {/* Gram-Schmidt Vectors */}
          {showGramSchmidt && (
            <line
              x1="0"
              y1="0"
              x2={gs.b2Star[0]}
              y2={gs.b2Star[1]}
              stroke="#a855f7"
              strokeWidth="2"
              strokeDasharray="3 3"
            />
          )}

          {/* Closest Vector Problem (CVP) target & line */}
          {targetPoint && closestPoint && (
            <g>
              <line
                x1={targetPoint.x}
                y1={targetPoint.y}
                x2={closestPoint.x}
                y2={closestPoint.y}
                stroke="#f59e0b"
                strokeWidth="1.5"
                strokeDasharray="3 3"
              />
              <circle cx={targetPoint.x} cy={targetPoint.y} r="5" fill="#f59e0b" />
              <text x={targetPoint.x + 8} y={targetPoint.y + 4} fill="#f59e0b" fontSize="10" fontFamily="sans-serif">
                Target t (CVP)
              </text>
            </g>
          )}

          {/* Origin */}
          <circle cx="0" cy="0" r="4" fill="#f8fafc" />
        </svg>

        {/* Legend Footer */}
        <div className="p-3 bg-slate-900/90 border-t border-slate-800 flex flex-wrap items-center justify-between text-xs text-slate-400 gap-2">
          <div className="flex items-center space-x-4">
            <span className="flex items-center space-x-1.5">
              <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 inline-block" />
              <span className="text-slate-300">b₁ vector</span>
            </span>
            <span className="flex items-center space-x-1.5">
              <span className="w-2.5 h-2.5 rounded-full bg-cyan-500 inline-block" />
              <span className="text-slate-300">b₂ vector</span>
            </span>
            <span className="flex items-center space-x-1.5">
              <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 ring-2 ring-emerald-500/40 inline-block" />
              <span className="text-slate-300">Shortest Non-Zero Vector (SVP)</span>
            </span>
          </div>

          <span className="text-slate-500 font-mono text-[11px]">
            Click canvas to move CVP target point
          </span>
        </div>
      </div>

      {/* Why Quantum Computers Fail on High-Dim Lattices */}
      <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-3 text-xs">
        <h4 className="text-sm font-bold text-slate-200 flex items-center space-x-2">
          <Shield className="h-4 w-4 text-cyan-400" />
          <span>Why Post-Quantum Lattices Defeat Quantum Attacks</span>
        </h4>
        <p className="text-slate-400 leading-relaxed">
          Shor's algorithm relies on Quantum Phase Estimation over periodic cyclic groups (Z / N Z)* to factor RSA or compute discrete logarithms in polynomial time O((log N)^3). In contrast, finding the shortest vector in high-dimensional lattices (n = 256 to 1024) lacks hidden abelian period structures. The best known quantum lattice attacks (such as quantum sieving) have exponential time complexity 2^(c · n), preserving cryptanalytic security indefinitely.
        </p>
      </div>
    </div>
  );
};
